import * as T from "./technologies";
import * as C from "./tags";

export default [
  {
    id: 1,
    title: "Weather",
    url: "https://weather-dashboard-eosin.vercel.app/",
    githubUrl: "https://github.com/gsajulia/weather-dashboard",
    description: "Weather of São Paulo using Open meteo API",
    priority: 1,
    img: "https://raw.githubusercontent.com/gsajulia/weather-dashboard/main/src/assets/weatherDashboard.gif",
    tags: [T.reactSkill, T.javascriptSkill, T.cssSkill, T.htmlSkill],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 2,
    title: "Kanban",
    url: "https://github.com/gsajulia/kanban-boracodar",
    githubUrl: "",
    description:
      "A project that simulates a kanban board, enabling card management and filters",
    priority: 1,
    img: "https://raw.githubusercontent.com/gsajulia/kanban-boracodar/main/src/assets/kanban.gif",
    tags: [T.reactSkill, T.javascriptSkill, T.cssSkill, T.htmlSkill],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 3,
    title: "Character Card",
    url: "https://character-card-cyan.vercel.app/",
    githubUrl: "https://github.com/gsajulia/character-card",
    description: "Cards with descriptions of Star Wars characters",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/character-card/main/public/card.gif",
    tags: [T.reactSkill, T.javascriptSkill, T.cssSkill, T.htmlSkill],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 4,
    title: "Calculator",
    url: "https://mycalculator-juh-rick.vercel.app/",
    githubUrl: "https://github.com/gsajulia/calculator-rocketseat",
    description:
      "Project with the calculation functions and interface of a calculator",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/calculator-rocketseat/main/.github/calculator.jpg",
    tags: [T.reactSkill, T.javascriptSkill, T.cssSkill, T.htmlSkill],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 5,
    title: "Ticket",
    url: "https://boarding-pass-rocketseat.vercel.app/",
    githubUrl: "https://github.com/gsajulia/boarding-pass-rocketseat",
    description:
      "Ensure that the data that the boarding pass contains were acquired on a previous page, through the user's choices",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/boarding-pass-rocketseat/main/src/assets/demo.gif",
    tags: [T.reactSkill, T.javascriptSkill, T.cssSkill, T.htmlSkill],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 6,
    title: "Carnival",
    url: "https://carnaval-searcher.vercel.app/",
    githubUrl: "https://github.com/gsajulia/carnaval-searcher/",
    description: "Website to search for carnival blocks with search and map",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/carnaval-searcher/master/src/assets/gif-carnaval-web.gif",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.reactLeafletSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 7,
    title: "Dashboard of Sales",
    url: "https://dashboard-sales-rocketseat-challenge.vercel.app/",
    githubUrl: "https://github.com/gsajulia/dashboard-sales",
    description:
      "Sales dashboard with graphs of the respective indexes inserted",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/dashboard-sales/main/src/assets/dashboard.gif",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.apexChartsSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 8,
    title: "Currency Converter",
    url: "https://currency-converter-rocketseat.vercel.app/",
    githubUrl: "https://github.com/gsajulia/currency-converter-rocketseat",
    description: "Project of a currency converter with graphics",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/currency-converter-rocketseat/main/src/assets/currency.gif",
    tags: [T.reactSkill, T.javascriptSkill, T.cssSkill, T.htmlSkill],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 9,
    title: "Credit Card",
    url: "https://credit-card-form-chi.vercel.app/",
    githubUrl: "https://github.com/gsajulia/credit-card-form",
    description: "Interactive credit card form",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/credit-card-form/main/src/app/assets/figma.png",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 10,
    title: "Login",
    url: "https://login-page-rocketseat.vercel.app/",
    githubUrl: "https://github.com/gsajulia/login-page-rocketseat",
    description: "Simple project that simulates a login page",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/login-page-rocketseat/main/src/assets/login-file.gif",
    tags: [T.reactSkill, T.javascriptSkill, T.cssSkill, T.htmlSkill],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 11,
    title: "Upload Component",
    url: "https://component-upload-boracodar.vercel.app/",
    githubUrl: "https://github.com/gsajulia/credit-card-form",
    description: "Simple uploader component",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/component-upload-boracodar/main/src/app/assets/uploader.gif",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 12,
    title: "Princing",
    url: "https://pricing-table-omega.vercel.app/",
    githubUrl: "https://github.com/gsajulia/pricing-table",
    description: "Interactive pricing table page",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/pricing-table/main/assets/pricing.gif",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 13,
    title: "Contacts",
    url: "https://contact-page-phi.vercel.app/",
    githubUrl: "https://github.com/gsajulia/contact-page",
    description: "Contacts page website",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/contact-page/main/public/figma.png",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 14,
    title: "Transport Widget",
    url: "https://transport-widget.vercel.app/",
    githubUrl: "https://github.com/gsajulia/transport-widget",
    description: "Website inspired on transport apps",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/transport-widget/main/public/transport-widget.png",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 15,
    title: "Profile Settings",
    url: "https://shopping-cart-kohl-one.vercel.app/",
    githubUrl: "https://github.com/gsajulia/profile-settings",
    description: "User settings profile",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/pricing-table/main/assets/pricing.gif",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 16,
    title: "Multi-Step Form",
    url: "https://multi-step-form-gilt-nine.vercel.app/",
    githubUrl: "https://github.com/gsajulia/multi-step-form",
    description: "Register user Form page",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/multi-step-form/main/public/stepForm.gif",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 17,
    title: "VR Player",
    url: "https://multi-step-form-gilt-nine.vercel.app/",
    githubUrl: "https://github.com/gsajulia/player-vr",
    description: "Layout of VR Player",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/player-vr/main/public/video.gif",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 18,
    title: "Pamonha",
    url: "https://receita-pamonha.vercel.app/",
    githubUrl: "https://github.com/gsajulia/receita-pamonha",
    description: "Recipes page",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/receita-pamonha/main/public/pamonha.gif",
    tags: [
      T.reactSkill,
      T.javascriptSkill,
      T.cssSkill,
      T.htmlSkill,
      T.nextSkill,
    ],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
  {
    id: 19,
    title: "Water Quality",
    url: "https://mukaschultze.github.io/qualidade-agua/",
    githubUrl: "https://github.com/mukaschultze/qualidade-agua",
    description: "User settings profile",
    priority: 2,
    img: "https://raw.githubusercontent.com/gsajulia/pricing-table/main/assets/pricing.gif",
    tags: [T.angularSkill, T.javascriptSkill, T.cssSkill, T.htmlSkill],
    categories: [C.frontendTag],
    mainCategoryId: C.frontendTag.id,
  },
];
